logging:
  level:
    org.springframework : info

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  messages:
    basename: messages

  # default basic security credentials
  security:
    user:
      name: user
      password: password

# Trim this down for production to prevent performance impact
management:
  endpoints:
    web:
      exposure:
        include: "*"
