logging:
  level:
    org.springframework : info

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  messages:
    basename: messages

# Trim this down for production to prevent performance impact
management:
  endpoints:
    web:
      exposure:
        include: "*"
